apiVersion: v1
kind: Service
metadata:
  name: spire-oidc
  namespace: spire
spec:
  type: NodePort
  selector:
    app: spire-server
  ports:
    - name: http
      port: 8082
      targetPort: oidc-port
    - name: https
      port: 8083
      targetPort: oidc-https-port